-- This file seeded the original per-department model ('Computer Science',
-- 'Electrical Engineering' departments with their own keys). That model was
-- retired by migration 20260625221600_faculties_and_admin_authoriser.sql,
-- which deletes every row in units/keys/requests and reseeds the faculty +
-- Administration model (units.id 10000000-...-0001..0004 and ...-00a0), so
-- this file's inserts now collide with those on primary key.
--
-- Local dev and pgTAP already get realistic seed data for free from that
-- migration (and 20260613071010_departments_faculty_and_seed.sql, which adds
-- more Engineering/Management Sciences departments before the faculty
-- migration wipes and rebuilds around faculties). No separate seed step is
-- needed; this file is intentionally empty.
