import Link from 'next/link';

import { BotIcon, FlagIcon, KeyRoundIcon, RotateCcwIcon } from 'lucide-react';

import { Button } from '@/components/ui/button';

import { ReportsDialog } from '@/app/cso/reports/_components/reports-dialog';

// Types

export type Report = {
  id: string;
  shift: number;
  date: string;
  timeRange: string;
  officers: string[];
  issued: number;
  returned: number;
  flagged: number;
};

// Helpers

export const formatDate = (iso: string) =>
  new Date(iso).toLocaleDateString('en-GB', {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });

export const formatTime = (iso: string) =>
  new Date(iso).toLocaleTimeString('en-GB', {
    hour: '2-digit',
    minute: '2-digit',
  });

export function groupByDay(
  reports: Report[]
): { day: string; items: Report[] }[] {
  const groups: Record<string, Report[]> = {};
  reports.forEach((r) => {
    if (!groups[r.date]) groups[r.date] = [];
    groups[r.date].push(r);
  });
  return Object.entries(groups).map(([day, items]) => ({ day, items }));
}

// Component

type Props = {
  reportGroups: { day: string; items: Report[] }[];
  hasNextPage: boolean;
  isFetchingNextPage: boolean;
  onLoadMore: () => void;
};

export const ReportsList = ({
  reportGroups,
  hasNextPage,
  isFetchingNextPage,
  onLoadMore,
}: Props) => {
  return (
    <>
      <div className="flex flex-col gap-8">
        {reportGroups.map((group) => (
          <div key={group.day} className="flex flex-col gap-3">
            <h2 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              {group.day}
            </h2>
            {group.items.map((report) => (
              <div
                key={report.id}
                className="flex flex-col gap-4 rounded-lg border border-border bg-card p-5 shadow-[0_2px_4px_rgba(15,23,42,0.06)]"
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="flex flex-col gap-0.5">
                    <Link
                      href={`/cso/reports/${report.id}`}
                      className="text-sm font-semibold text-foreground underline-offset-4 hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
                    >
                      Shift {report.shift} — {report.date}, {report.timeRange}
                    </Link>
                    <span className="text-xs text-muted-foreground">
                      {report.officers.join(', ')}
                    </span>
                  </div>
                  <div className="flex shrink-0 items-center gap-2">
                    <ReportsDialog report={report} />
                  </div>
                </div>
                <div className="flex flex-wrap items-center gap-4 text-xs">
                  <span className="flex items-center gap-1.5 text-muted-foreground">
                    <KeyRoundIcon
                      className="size-3.5 text-primary"
                      aria-hidden="true"
                    />
                    {report.issued} issued
                  </span>
                  <span className="flex items-center gap-1.5 text-muted-foreground">
                    <RotateCcwIcon
                      className="size-3.5 text-emerald-600"
                      aria-hidden="true"
                    />
                    {report.returned} returned
                  </span>
                  {report.flagged > 0 && (
                    <span className="flex items-center gap-1.5 text-destructive">
                      <FlagIcon className="size-3.5" aria-hidden="true" />
                      {report.flagged} flagged
                    </span>
                  )}
                </div>
                <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                  <BotIcon className="size-3.5" aria-hidden="true" />
                  <span>Generated by AI from shift event data</span>
                </div>
              </div>
            ))}
          </div>
        ))}
      </div>

      {hasNextPage && (
        <div className="flex justify-center">
          <Button
            variant="outline"
            onClick={onLoadMore}
            disabled={isFetchingNextPage}
            aria-busy={isFetchingNextPage}
          >
            {isFetchingNextPage ? 'Loading…' : 'Load more'}
          </Button>
        </div>
      )}
    </>
  );
};
