import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';

import { logger } from '@/lib/logger';
import { createAdminClient } from '@/lib/supabase/admin';
import { createServerClient } from '@/lib/supabase/server';
import { err, ok } from '@/types/api';

const bodySchema = z.object({
  shift_id: z.string().uuid(),
});

const mapRpcError = (msg: string): { status: number; message: string } => {
  if (msg.includes('NOT_AUTHENTICATED'))
    return { status: 401, message: 'Not authenticated' };
  if (msg.includes('FORBIDDEN')) return { status: 403, message: 'Forbidden' };
  if (msg.includes('NOT_FOUND'))
    return { status: 404, message: 'Shift not found' };
  if (msg.includes('CONFLICT'))
    return { status: 409, message: 'Report already generated for this shift' };
  return { status: 500, message: 'Internal error' };
};

const buildTemplateFallback = (shiftId: string, events: unknown[]): string => {
  const count = Array.isArray(events) ? events.length : 0;
  return [
    `## Shift Report`,
    ``,
    `**Shift ID:** ${shiftId}`,
    `**Generated at:** ${new Date().toISOString()}`,
    ``,
    `### Summary`,
    `This shift recorded ${count} audit event(s). Gemini was unavailable; this report was generated from a template.`,
    ``,
    `### Outstanding Keys`,
    `_See the outstanding keys dashboard for current status._`,
    ``,
    `### Chain of Custody`,
    `All key transactions are available in the audit log.`,
    ``,
    `---`,
    `*Generated from shift event data (template fallback — Gemini unavailable)*`,
  ].join('\n');
};

export const POST = async (request: NextRequest) => {
  const supabase = await createServerClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user)
    return NextResponse.json(err('Unauthorized', 401), { status: 401 });

  const { data: profile } = await supabase
    .from('profiles')
    .select('role, department_id')
    .eq('id', user.id)
    .single();
  if (!profile)
    return NextResponse.json(err('Unauthorized', 401), { status: 401 });
  if (profile.role !== 'CSO')
    return NextResponse.json(err('Forbidden', 403), { status: 403 });

  const body = await request.json().catch(() => null);
  const parsed = bodySchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(err('Invalid request body', 422), { status: 422 });
  }

  const { shift_id } = parsed.data;

  // Create the placeholder shift_reports row via RPC (handles uniqueness + audit entry).
  const { data: rpcData, error: rpcError } = await supabase.rpc(
    'generate_shift_report',
    {
      p_shift_id: shift_id,
    }
  );

  if (rpcError) {
    const mapped = mapRpcError(rpcError.message);
    if (mapped.status === 500) {
      const ref = crypto.randomUUID();
      logger.error('generate_shift_report RPC failed', {
        err: rpcError.message,
        ref,
      });
      return NextResponse.json(err(`Internal error. Ref: ${ref}`, 500), {
        status: 500,
      });
    }
    return NextResponse.json(err(mapped.message, mapped.status), {
      status: mapped.status,
    });
  }

  const result = Array.isArray(rpcData) ? rpcData[0] : rpcData;
  if (!result?.report_id) {
    const ref = crypto.randomUUID();
    logger.error('generate_shift_report RPC returned empty result', { ref });
    return NextResponse.json(err(`Internal error. Ref: ${ref}`, 500), {
      status: 500,
    });
  }

  const reportId: string = result.report_id;

  // Fetch audit events for this shift to feed to Gemini.
  const { data: events } = await supabase
    .from('audit_log')
    .select('event, actor_role, target_type, target_id, payload, occurred_at')
    .gte(
      'occurred_at',
      (
        await supabase
          .from('shifts')
          .select('started_at')
          .eq('id', shift_id)
          .single()
      ).data?.started_at ?? new Date(0).toISOString()
    )
    .order('occurred_at', { ascending: true });

  let markdown: string;
  let timeline: unknown[] = [];

  const geminiKey = process.env.GEMINI_API_KEY;

  if (geminiKey) {
    try {
      const prompt = [
        'You are a security shift report assistant for SmartKey, a key management system.',
        'Given the following audit log events from a security shift, produce a structured report.',
        'Return a JSON object with these fields:',
        '  "markdown": a markdown string containing:',
        '    - A 2-3 sentence summary',
        '    - "## Outstanding Keys" section',
        '    - "## Flagged Events" section (list any unusual activity)',
        '    - "## Unresolved Incidents" section',
        '    - "## Chain of Custody" section',
        '    - A footer: "*Generated by AI from shift event data*"',
        '  "timeline": an array of { time, event, description } objects for the ShiftTimeline component',
        '',
        'Audit events:',
        JSON.stringify(events ?? [], null, 2),
      ].join('\n');

      const geminiResponse = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${geminiKey}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: { responseMimeType: 'application/json' },
          }),
        }
      );

      if (geminiResponse.ok) {
        const geminiJson = await geminiResponse.json();
        const rawText: string =
          geminiJson?.candidates?.[0]?.content?.parts?.[0]?.text ?? '';
        const parsed = JSON.parse(rawText) as {
          markdown?: string;
          timeline?: unknown[];
        };
        markdown =
          parsed.markdown ?? buildTemplateFallback(shift_id, events ?? []);
        timeline = parsed.timeline ?? [];
      } else {
        logger.error('Gemini API error', { status: geminiResponse.status });
        markdown = buildTemplateFallback(shift_id, events ?? []);
      }
    } catch (e) {
      logger.error('Gemini call threw', { err: String(e) });
      markdown = buildTemplateFallback(shift_id, events ?? []);
    }
  } else {
    markdown = buildTemplateFallback(shift_id, events ?? []);
  }

  // Update the shift_reports row with the generated content.
  // RLS blocks direct UPDATE for authenticated users — use the service-role
  // admin client so this write succeeds regardless of session role.
  const adminClient = createAdminClient();
  const generatedAt = new Date().toISOString();
  await adminClient
    .from('shift_reports')
    .update({
      markdown,
      timeline: timeline as never,
      metadata: {
        generated_at: generatedAt,
        source: geminiKey ? 'gemini' : 'template',
      },
    })
    .eq('id', reportId);

  return NextResponse.json(
    ok({ report_id: reportId, generated_at: generatedAt }),
    { status: 201 }
  );
};
