import type { ReportEvent, TimelineEntry } from './types';

// The structured instruction sent to Gemini. Asks for a JSON object so the
// response can be parsed deterministically (see parser.ts). The markdown must
// carry the five required sections plus the AI disclosure footer.
export const buildReportPrompt = (events: ReportEvent[]): string =>
  [
    'You are a security shift report assistant for SmartKey, a key management system at the University of Lagos Senate Building.',
    'Given the following audit log events from a security shift, produce a structured report.',
    'Respond with a raw JSON object only — no markdown code fences, no extra text before or after.',
    'The JSON must have exactly these two fields:',
    '  "markdown": a markdown string containing:',
    '    - A 2-3 sentence summary paragraph',
    '    - "## Outstanding Keys" section',
    '    - "## Flagged Events" section (list any high-risk or unusual activity)',
    '    - "## Unresolved Incidents" section',
    '    - "## Chain of Custody" section summarising key handovers',
    '    - A footer line: "*Generated by AI from shift event data*"',
    '  "timeline": an array of objects, each with { "time": "HH:MM", "event": "EVENT_NAME", "description": "plain English description" }',
    '',
    'Audit events for this shift:',
    JSON.stringify(events, null, 2),
  ].join('\n');

// Deterministic fallback used when Gemini is unavailable, the quota is exhausted,
// or the response cannot be parsed. Produces a structured (if plainer) report so
// the feature always yields output. See docs/AI.md "template fallback".
export const buildTemplateReport = (
  shiftId: string,
  events: ReportEvent[]
): { markdown: string; timeline: TimelineEntry[] } => {
  const count = events.length;
  const markdown = [
    `## Shift Report`,
    ``,
    `**Shift ID:** ${shiftId}`,
    `**Generated at:** ${new Date().toISOString()}`,
    ``,
    `### Summary`,
    `This shift recorded ${count} audit event(s). Gemini was unavailable; this report was generated from a template.`,
    ``,
    `### Outstanding Keys`,
    `_See the outstanding keys dashboard for current status._`,
    ``,
    `### Chain of Custody`,
    `All key transactions are available in the audit log.`,
    ``,
    `---`,
    `*Generated from shift event data (template fallback — Gemini unavailable)*`,
  ].join('\n');

  return { markdown, timeline: [] };
};
