-- Migration: shift_reports, shift_report_comments
-- shift_reports stores the Gemini-generated narrative summary for a shift.
-- It is IMMUTABLE after insert — RLS will deny UPDATE and DELETE for all roles
-- (enforced in Issue #11 RLS migration). The UNIQUE constraint on shift_id
-- guarantees exactly one report per shift.
--
-- shift_report_comments are also IMMUTABLE after insert. CSO may add commentary
-- to a report; comments appear alongside the report in PDF exports. Once written
-- a comment cannot be altered or deleted — same principle as the audit log.
--
-- Both tables carry "AI-generated" metadata so the UI can display the
-- required "Generated by AI from shift event data" disclosure.

-- shift_reports

create table public.shift_reports (
  id           uuid        primary key default gen_random_uuid(),
  -- UNIQUE: exactly one report per shift
  shift_id     uuid        not null unique references public.shifts(id) on delete restrict,
  -- Long-form Gemini prose output in Markdown
  markdown     text        not null,
  -- Structured event timeline extracted from the Gemini response (for ShiftTimeline component)
  timeline     jsonb       not null default '[]',
  -- Additional metadata: model version, token count, fallback flag, etc.
  metadata     jsonb       not null default '{}',
  generated_at timestamptz not null default now()

  -- IMMUTABLE: RLS denies UPDATE and DELETE for all roles (applied in Issue #11).
);

alter table public.shift_reports enable row level security;

-- Index: chronological listing on CSO Reports page
create index idx_shift_reports_generated_at on public.shift_reports(generated_at desc);

-- shift_report_comments

create table public.shift_report_comments (
  id         uuid        primary key default gen_random_uuid(),
  report_id  uuid        not null references public.shift_reports(id) on delete restrict,
  -- Only CSO may add comments (enforced in Issue #11 RLS)
  author_id  uuid        not null references public.profiles(id) on delete restrict,
  text       text        not null,
  created_at timestamptz not null default now()

  -- IMMUTABLE: RLS denies UPDATE and DELETE (applied in Issue #11).
);

alter table public.shift_report_comments enable row level security;

-- Index: all comments for a report (loaded together with the report)
create index idx_shift_report_comments_report_id on public.shift_report_comments(report_id);
-- Index: CSO's own comment history
create index idx_shift_report_comments_author_id on public.shift_report_comments(author_id);
