-- =============================================================================
-- Migration: incidents
-- =============================================================================
-- Incident log: append-only record of security incidents raised during shifts.
-- Every incident has a unique human-readable reference number (INC-YYYY-NNNN)
-- generated by a sequence-backed trigger so references are stable and
-- monotonically increasing within a year.
--
-- Severity HIGH automatically triggers AI summary generation and a CSO alert
-- (handled at the application layer; the table itself is passive).
--
-- IMPORTANT: The application database role must have INSERT permission only.
-- UPDATE and DELETE on this table must be explicitly revoked at the role level
-- to match the tamper-evidence requirement of a physical incident book.
-- RLS policies enforcing this are applied in Issue #11.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Sequence for human-readable incident references (INC-YYYY-NNNN)
-- ---------------------------------------------------------------------------

create sequence public.incident_reference_seq start 1;

-- ---------------------------------------------------------------------------
-- incidents
-- ---------------------------------------------------------------------------

create table public.incidents (
  id                uuid                       primary key default gen_random_uuid(),
  -- Human-readable stable reference, e.g. "INC-2026-0042"
  reference         text                       not null unique
                      default ('INC-' || to_char(now(), 'YYYY') || '-'
                               || lpad(nextval('public.incident_reference_seq')::text, 4, '0')),
  shift_id          uuid                       not null references public.shifts(id) on delete restrict,
  logged_by         uuid                       not null references public.profiles(id) on delete restrict,
  type              public.incident_type       not null,
  severity          public.incident_severity   not null,
  description       text                       not null,
  -- Optional links to the key or person involved
  related_key_id    uuid                       references public.keys(id) on delete set null,
  related_person_id uuid                       references public.profiles(id) on delete set null,
  photo_url         text,
  status            public.incident_status     not null default 'OPEN',
  occurred_at       timestamptz                not null,
  logged_at         timestamptz                not null default now()

  -- APPEND-ONLY: UPDATE and DELETE revoked for all roles (applied in Issue #11).
);

alter table public.incidents enable row level security;

-- Index: severity filter for CSO alert feed (HIGH incidents shown prominently)
create index idx_incidents_severity on public.incidents(severity);
-- Index: status filter (OPEN incidents need attention)
create index idx_incidents_status on public.incidents(status);
-- Index: shift-scoped incident list
create index idx_incidents_shift_id on public.incidents(shift_id);
-- Index: reverse-chronological display for CSO
create index idx_incidents_logged_at on public.incidents(logged_at desc);
-- Index: related key lookups
create index idx_incidents_related_key_id on public.incidents(related_key_id)
  where related_key_id is not null;
-- Index: related person lookups
create index idx_incidents_related_person_id on public.incidents(related_person_id)
  where related_person_id is not null;
